name: 'setup-pkl-action'

description: 'Setup PKL CLI.'

branding:
  icon: package
  color: blue

inputs:
  version:
    description: Desired pkl version.
    default: '0.26.0'

runs:
  using: 'node20'
  main: 'dist/index.js'
