name: Release

on:
  push:
    branches:
      - main

env:
  GIT_USER_EMAIL: ${{ secrets.GIT_EMAIL }}
  GIT_USER_NAME: ${{ secrets.GIT_NAME }}

permissions:
  contents: write
  packages: write

jobs:
  bump_version:
    if: "!startsWith(github.event.head_commit.message, 'bump:') && !startsWith(github.event.head_commit.message, 'ci:')"
    runs-on: ubuntu-latest
    name: 'Bump version'
    outputs:
      version: ${{ steps.cz.outputs.version }}
    steps:
      - name: Check out
        uses: actions/checkout@v4.1.5
        with:
          fetch-depth: 0
          token: '${{ secrets.ACCESS_TOKEN }}'
          ref: 'main'

      - name: Config Git User
        run: |
          git config --local user.email "$GIT_USER_EMAIL"
          git config --local user.name "$GIT_USER_NAME"
          git config --local pull.ff only

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.11

      - name: Create bump and changelog
        id: cz
        run: |
          python -m pip install -U commitizen
          cz bump --yes
          export REV=`cz version --project`
          echo "version=\"v$REV\"" >> $GITHUB_OUTPUT

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          branch: 'main'
          directory: .
          tags: true

      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"

  release:
    name: Release version
    runs-on: ubuntu-latest
    needs:
      - bump_version
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: main

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          gh release create ${{ needs.bump_version.outputs.version }} \
            --title ${{ needs.bump_version.outputs.version }} \
            --target main \
            --verify-tag \
            --latest
